//======This particular is only used as barrel no scripting code is allowed to write here====
export * from "./../UserRoutes";
export * from "./../LoginRoutes";
export * from "./../ModuleRoutes";
export * from "./../RoleRoutes";
export * from "./../ProfileRoutes";
export * from "./../PermissionRoutes";
export * from "./../RolePermissionRoutes";
export * from "./../UserRoleRoutes";
export * from "./../BusinessGroupRoutes";
export * from "./../LeadRoutes";
export * from "./../TagRoutes";
export * from "./../TaskGroupRoutes";
export * from "./../TaskRoutes";
export * from "./../ContactRoutes";
export * from "./../CompanyRoutes";
export * from "./../StatusFlowRoutes";
export * from "./../ReleaseRoutes";
export * from "./../MailServerRoutes";
export * from "./../OpportunityRoutes";
export * from "./../AccountRoutes";
export * from "./../WorkSpaceRoutes";
export * from "./../AppletRoutes";
export * from "./../ListRoutes";
export * from "./../ListItemRoutes";
export * from "./../ActivityLogRoutes";
export * from "./../ApprovalRoutes";
export * from "./../EodRoutes"
export * from "./../RoleWorkspacePermissionRoutes"
export * from "./../EmployeeRoutes"

